// lib/writing/export/gcode_exporter.dart
import 'package:flutter/material.dart' show Offset;

import '../model/geometry.dart';
import '../model/toolpath.dart';
import 'visual_compensation.dart';

enum PenControlMode { macro, zHeight }

class GcodeExportOptions {
  final PenControlMode penMode;

  final double travelSpeedMmPerS;
  final double writeSpeedMmPerS;

  final String penUpCmd;
  final String penDownCmd;

  final double zUpMm;
  final double zDownMm;

  final int decimals;
  final bool addComments;
  final bool mirrorX;
  final bool mirrorY;
  final double? pageWidthMm;
  final double? pageHeightMm;
  final double defaultZMm;
  final VisualCompensationTransform? visualCompensation;

  const GcodeExportOptions({
    this.penMode = PenControlMode.macro,
    this.travelSpeedMmPerS = 80,
    this.writeSpeedMmPerS = 25,
    this.penUpCmd = 'PEN_UP',
    this.penDownCmd = 'PEN_DOWN',
    this.zUpMm = 5.0,
    this.zDownMm = 0.0,
    this.decimals = 3,
    this.addComments = true,
    this.mirrorX = false,
    this.mirrorY = false,
    this.pageWidthMm,
    this.pageHeightMm,
    this.defaultZMm = 0.0,
    this.visualCompensation,
  });

  int get travelF => (travelSpeedMmPerS * 60).round();
  int get writeF => (writeSpeedMmPerS * 60).round();
}

class GcodeExporter {
  String export(
    ToolPath toolPath, {
    GcodeExportOptions opt = const GcodeExportOptions(),
    Offset? startPointOffset,
    double? startPointZ,
  }) {
    final sb = StringBuffer();
    final zOrigin = startPointZ ?? opt.defaultZMm;
    final visualCompensation = opt.visualCompensation;
    final hasManualStartOffset = startPointOffset != null;

    if (opt.mirrorX && opt.pageWidthMm == null) {
      throw ArgumentError.value(
        opt.pageWidthMm,
        'pageWidthMm',
        'Required when mirrorX is enabled.',
      );
    }
    if (opt.mirrorY && opt.pageHeightMm == null) {
      throw ArgumentError.value(
        opt.pageHeightMm,
        'pageHeightMm',
        'Required when mirrorY is enabled.',
      );
    }
    void line(String s) => sb.writeln(s);
    String fmt(double v) => v.toStringAsFixed(opt.decimals);
    String xyz(Vec2 p) => 'X${fmt(p.x)} Y${fmt(p.y)} Z${fmt(zOrigin)}';
    final anchorPoint = !hasManualStartOffset
        ? null
        : _firstPathPoint(toolPath);

    Vec2 mirrorPoint(Vec2 p) {
      final x = opt.mirrorX ? opt.pageWidthMm! - p.x : p.x;
      final y = opt.mirrorY ? opt.pageHeightMm! - p.y : p.y;
      return Vec2(x, y);
    }

    Vec2 applyMachineTransform(Vec2 p) {
      final mapped = mirrorPoint(p);
      final origin = startPointOffset;
      final machinePoint = origin == null
          ? mapped
          : Vec2(
              origin.dx +
                  mapped.x -
                  (anchorPoint == null ? 0.0 : mirrorPoint(anchorPoint).x),
              origin.dy +
                  mapped.y -
                  (anchorPoint == null ? 0.0 : mirrorPoint(anchorPoint).y),
            );
      return visualCompensation?.correctMachinePoint(machinePoint) ??
          machinePoint;
    }

    Vec2 applyCommandCompensation(Vec2 p) {
      return visualCompensation?.correctMachinePoint(p) ?? p;
    }

    String correctionComment() {
      if (visualCompensation == null) return '';
      return ' ; visual XY precomp';
    }

    void writeMove(String motion, Vec2 point, int feed, {String? comment}) {
      line(
        '$motion ${xyz(point)} F$feed'
        '${comment ?? correctionComment()}',
      );
    }

    if (opt.addComments) {
      line('; Generated by Delta Writer Client');
      line('; Coord: paper top-left origin before export transform, unit=mm');
      if (opt.pageWidthMm != null || opt.pageHeightMm != null) {
        line(
          '; Page: X=${opt.pageWidthMm ?? '-'} Y=${opt.pageHeightMm ?? '-'} mm',
        );
      }
      if (opt.mirrorX || opt.mirrorY) {
        line(
          '; ExportTransform: '
          'mirrorX=${opt.mirrorX} pageWidth=${opt.pageWidthMm ?? '-'} '
          'mirrorY=${opt.mirrorY} pageHeight=${opt.pageHeightMm ?? '-'}',
        );
      }
      if (startPointOffset != null) {
        line(
          '; StartPointOffset: X=${startPointOffset.dx.toStringAsFixed(2)}, '
          'Y=${startPointOffset.dy.toStringAsFixed(2)}, '
          'Z=${zOrigin.toStringAsFixed(2)} mm',
        );
      }
      if (visualCompensation != null) {
        line('; VisualCompensation: enabled ${visualCompensation.summary}');
        line('; VisualCompensationMode: machine command XY precompensation');
      }
      line('; PenMode: ${opt.penMode.name}');
      line('; TravelSpeed: ${opt.travelSpeedMmPerS} mm/s');
      line('; WriteSpeed: ${opt.writeSpeedMmPerS} mm/s');
    }
    line('G90');
    line('G21');

    Vec2? cur;
    bool penIsDown = false;

    _emitPenUp(line, opt, zOrigin);
    if (hasManualStartOffset) {
      final start = applyCommandCompensation(
        Vec2(startPointOffset.dx, startPointOffset.dy),
      );
      writeMove('G0', start, opt.travelF);
      cur = anchorPoint;
    }

    void ensureAtWithPenUp(Vec2 p) {
      final adjusted = applyMachineTransform(p);
      if (cur == null || !_samePoint(cur!, p)) {
        if (penIsDown) {
          _emitPenUp(line, opt, zOrigin);
          penIsDown = false;
        }
        writeMove('G0', adjusted, opt.travelF);
        cur = p;
      }
    }

    void ensurePenDown() {
      if (!penIsDown) {
        _emitPenDown(line, opt, zOrigin);
        penIsDown = true;
      }
    }

    for (final pl in toolPath.polylines) {
      if (pl.points.length < 2) continue;

      final pts = pl.points;
      final start = pts.first;

      if (!pl.penDown) {
        if (penIsDown) {
          _emitPenUp(line, opt, zOrigin);
          penIsDown = false;
        }

        ensureAtWithPenUp(start);

        for (int i = 1; i < pts.length; i++) {
          final p = pts[i];
          final adjusted = applyMachineTransform(p);
          writeMove('G0', adjusted, opt.travelF);
          cur = p;
        }
      } else {
        ensureAtWithPenUp(start);
        ensurePenDown();

        for (int i = 1; i < pts.length; i++) {
          final p = pts[i];
          final adjusted = applyMachineTransform(p);
          writeMove('G1', adjusted, opt.writeF);
          cur = p;
        }
      }
    }

    _emitPenUp(line, opt, zOrigin);
    line('M400');
    line('G28 ; auto home after print');
    line('M400');
    line('G28 ; repeat home after print');
    if (opt.addComments) line('; End');

    return sb.toString();
  }

  bool _samePoint(Vec2 a, Vec2 b) {
    const eps = 1e-6;
    return (a.x - b.x).abs() < eps && (a.y - b.y).abs() < eps;
  }

  Vec2? _firstPathPoint(ToolPath toolPath) {
    for (final polyline in toolPath.polylines) {
      if (polyline.points.length >= 2) return polyline.points.first;
    }
    return null;
  }

  void _emitPenUp(
    void Function(String) line,
    GcodeExportOptions opt,
    double zOrigin,
  ) {
    switch (opt.penMode) {
      case PenControlMode.macro:
        line(opt.penUpCmd);
        break;
      case PenControlMode.zHeight:
        line('G0 Z${(zOrigin + opt.zUpMm).toStringAsFixed(opt.decimals)}');
        break;
    }
  }

  void _emitPenDown(
    void Function(String) line,
    GcodeExportOptions opt,
    double zOrigin,
  ) {
    switch (opt.penMode) {
      case PenControlMode.macro:
        line(opt.penDownCmd);
        break;
      case PenControlMode.zHeight:
        line('G0 Z${(zOrigin + opt.zDownMm).toStringAsFixed(opt.decimals)}');
        break;
    }
  }
}
