// lib/writing/export/gcode_exporter.dart
import '../model/toolpath.dart';
import '../model/geometry.dart';

enum PenControlMode {
  macro,   // PEN_UP / PEN_DOWN
  zHeight, // 用 Z_UP / Z_DOWN
}

class GcodeExportOptions {
  final PenControlMode penMode;

  // feedrate 用 mm/s 更符合你“写字速度”的直觉；导出时转 mm/min
  final double travelSpeedMmPerS; // G0
  final double writeSpeedMmPerS;  // G1

  // 宏模式
  final String penUpCmd;
  final String penDownCmd;

  // Z 抬笔模式（预留）
  final double zUpMm;
  final double zDownMm;

  // 小数位（太多会让文件变大）
  final int decimals;

  // 是否在输出中加入注释
  final bool addComments;

  const GcodeExportOptions({
    this.penMode = PenControlMode.macro,
    this.travelSpeedMmPerS = 80,
    this.writeSpeedMmPerS = 25,
    this.penUpCmd = 'PEN_UP',
    this.penDownCmd = 'PEN_DOWN',
    this.zUpMm = 5.0,
    this.zDownMm = 0.0,
    this.decimals = 3,
    this.addComments = true,
  });

  int get travelF => (travelSpeedMmPerS * 60).round(); // mm/min
  int get writeF => (writeSpeedMmPerS * 60).round();   // mm/min
}

class GcodeExporter {
  String export(ToolPath toolPath, {GcodeExportOptions opt = const GcodeExportOptions()}) {
    final sb = StringBuffer();

    void line(String s) => sb.writeln(s);

    String fmt(double v) => v.toStringAsFixed(opt.decimals);

    // ==== header ====
    if (opt.addComments) {
      line('; Generated by Delta Writer Client');
      line('; Coord: paper top-left origin (0,0), +X right, +Y down, unit=mm');
      line('; PenMode: ${opt.penMode.name}');
      line('; TravelSpeed: ${opt.travelSpeedMmPerS} mm/s');
      line('; WriteSpeed: ${opt.writeSpeedMmPerS} mm/s');
    }
    line('G90'); // absolute
    line('G21'); // mm

    // 初始笔状态：抬笔
    _emitPenUp(line, opt);

    Vec2? cur;
    bool penIsDown = false;

    // helper: move with pen-up to a point
    void ensureAtWithPenUp(Vec2 p) {
      if (cur == null || !_samePoint(cur!, p)) {
        if (penIsDown) {
          _emitPenUp(line, opt);
          penIsDown = false;
        }
        line('G0 X${fmt(p.x)} Y${fmt(p.y)} F${opt.travelF}');
        cur = p;
      }
    }

    // helper: switch pen down
    void ensurePenDown() {
      if (!penIsDown) {
        _emitPenDown(line, opt);
        penIsDown = true;
      }
    }

    // ==== body ====
    for (final pl in toolPath.polylines) {
      if (pl.points.length < 2) continue;

      final pts = pl.points;
      final start = pts.first;

      if (!pl.penDown) {
        // pen-up polyline: ensure pen up, then G0 along points
        if (penIsDown) {
          _emitPenUp(line, opt);
          penIsDown = false;
        }

        // 如果当前位置不在起点，先去起点
        ensureAtWithPenUp(start);

        // 沿 polyline 逐点 G0（你也可以未来优化为直接到终点）
        for (int i = 1; i < pts.length; i++) {
          final p = pts[i];
          line('G0 X${fmt(p.x)} Y${fmt(p.y)} F${opt.travelF}');
          cur = p;
        }
      } else {
        // pen-down polyline: 必须先到 start（且必须 pen-up），再 pen-down，再 G1
        ensureAtWithPenUp(start);
        ensurePenDown();

        for (int i = 1; i < pts.length; i++) {
          final p = pts[i];
          line('G1 X${fmt(p.x)} Y${fmt(p.y)} F${opt.writeF}');
          cur = p;
        }
      }
    }

    // ==== footer ====
    _emitPenUp(line, opt);
    line('M400'); // wait for moves to finish
    if (opt.addComments) line('; End');

    return sb.toString();
  }

  bool _samePoint(Vec2 a, Vec2 b) {
    // 容差比较，避免浮点误差导致重复移动
    const eps = 1e-6;
    return (a.x - b.x).abs() < eps && (a.y - b.y).abs() < eps;
  }

  void _emitPenUp(void Function(String) line, GcodeExportOptions opt) {
    switch (opt.penMode) {
      case PenControlMode.macro:
        line(opt.penUpCmd);
        break;
      case PenControlMode.zHeight:
        // 预留：以 G0 方式抬 Z
        line('G0 Z${opt.zUpMm.toStringAsFixed(opt.decimals)}');
        break;
    }
  }

  void _emitPenDown(void Function(String) line, GcodeExportOptions opt) {
    switch (opt.penMode) {
      case PenControlMode.macro:
        line(opt.penDownCmd);
        break;
      case PenControlMode.zHeight:
        line('G0 Z${opt.zDownMm.toStringAsFixed(opt.decimals)}');
        break;
    }
  }
}